version: '3.8'

services:
  ps_fatto:
    image: ${DOCKER_REGISTRY-}psfatto
    build:
      context: .
      dockerfile: /Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - sqlite-data:/app/db

volumes:
  sqlite-data: 
  
  